doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Discounts\Infrastructure\Persistence\Migration': '%kernel.project_dir%/src/Discounts/Infrastructure/Persistence/Doctrine/Migration'
    enable_profiler: false
