discount_calculate:
    path: /api/discounts/calculate
    controller: App\Discounts\Infrastructure\Controller\CalculateDiscountController::__invoke
    methods: GET
    requirements:
        _format: json